### ISSUE TITLE
Create project plan

### ISSUE THREAD

**Issue by djbpitt** [Data-Science-for-Linguists-2019/russian_rhyme#2]
<https://naraehan.github.io/Data-Science-for-Linguists-2019/project#plan>

* Create a repository within our GitHub class organization. Screenshots: the set up screen, after creation.
    - [x] Give it a descriptive name that is not too long. Good choice: “Inaugural-Address-Analysis”, bad: “Narae-Term-Project”.
    - [x] Provide a description. This is a short tagline that appears under your repo title. Start with something simple. Make sure your name is in there. (See the two screenshots above.)
    - [x] The repository should be public.
    - [x] Initialize with a README.
* This is YOUR repo! No forking necessary: just clone it and get to work.
* Your repo should have the following files:
    - [x] *README.md*: Include your name, project title, and a brief summary here.
    - [x] *LICENSE.md*: You will eventually need to specify a license for your project. Build it now as a place holder.
    - [x] *project_plan.md*: This is your project plan. Start with your project ideas document and polish it up.
    - [x] *progress_report.md*: This is where you will log your progress, newest entry on top. Add your first entry.
    - [x] *.gitignore*: Include the usual files and directories to be ignored.
* Can’t wait to get started? Read the following.
    * You are welcome to put other directories and files in your local repo as you see fit, but do NOT commit them to Git. Reason: once anything is on Git and GitHub, it’s always there (i.e., recoverable) as part of the commit history.
    * Likewise, don’t commit your data files yet. You are likely unsure at this stage whether or not you have the rights to share the data freely.
    - [x] A suggestion: create a directory called private/ where you will keep any private notes and data files. Add this directory to your .gitignore file.
    * Having said that, don’t be afraid to publish changes to your GitHub repo on an ongoing basis. The instructors have access to your repo’s state at any given point in time, so there is no need to keep your repo pristine & frozen until a grade is posted.

**Submission:** Your project repo counts as your submission.

**Comment by djbpitt** [comment]
Impeded while waiting for advice on data management

**Comment by djbpitt** [comment]
Temporize ...
